apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::994905724347:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1N99R3BEXSEYH
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::994905724347:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-02T19:10:28Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "14555"
  uid: b4b6aef7-f646-4048-a0d7-3edc5ed6d2d6
